INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (1, 'Bloomsbury Publishing',  'https://media-exp1.licdn.com/dms/image/C4E0BAQEDkPybVXr47Q/company-logo_200_200/0/1544531682586?e=2159024400&v=beta&t=JjAs9ok_PwgXA9CFsXKm3bt6fjbFI4N7SZRn4ajOUVg');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (102, 'Palok Publishers',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (105, 'গদ্যপদ্য',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (106, 'দি রয়েল পাবলিশার্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (109, 'প্রতিভা প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (110, 'কথামেলা প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (133, 'বেঙ্গল পাবলিকেশন্‌স',  'https://ds.rokomari.store/rokomari110/company/5cc15a9e8004_755.jpg');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (134, 'আদী প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (138, 'জ্যোৎস্না পাবলিশার্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (142, 'বিজয় প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (144, 'শুভ্র প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (150, 'আদিগন্ত প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (151, 'অন্যধারা',  'https://ds.rokomari.store/rokomari110/company/dac6d01b1_364.jpg');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (153, 'মহাকাল',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (157, 'মৌলি প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (158, 'শুভ প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (163, 'জয় প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (177, 'কুঁড়েঘর প্রকাশনী লিমিটেড',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (181, 'শুদ্ধস্বর',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (183, 'চমনপ্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (198, 'বিপ্লবীদের কথা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (199, 'শব্দশিল্প',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (209, 'প্রিয়মুখ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (211, 'তৃণলতা প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (215, 'শামস্‌ পাবলিকেশন্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (291, 'দ্বিমিক প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/436092935fd4_3594.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (293, 'হাতেখড়ি',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (303, 'ডেইলি স্টার বুকস',  'https://ds.rokomari.store/rokomari110/company/a0610fece_848.jpg');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (312, 'পুথিনিলয় প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (315, 'পাললিক সৌরভ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (317, 'আজাদ পাবলিকেশন্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (322, 'ক্র্যাট প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (327, 'রাত্রি প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (338, 'রাতুল গ্রন্থপ্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (343, 'মৌ প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (348, 'সংরক্ষণ প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (225, 'চন্দ্রদীপ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (226, 'গোল্ডেন বুকস',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (227, 'স্বরবৃত্ত প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (228, 'যুক্ত প্রকাশনা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (229, 'কবি প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (230, 'আলোঘর প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (237, 'শাহীন প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (238, 'সমগ্র প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (240, 'চিত্রা প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (244, 'মেলা প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (247, 'দেশ পাবলিকেশন’স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (251, 'রূপ প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (254, 'সাহস পাবলিকেশন্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (255, 'চৈতন্য',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (285, 'আপন প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (21, 'দ্বিমিক প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/436092935fd4_3594.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (42, 'বসুন্ধরা প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (44, 'স্টুডেন্ট ওয়েজ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (45, 'মনন প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (46, 'বাঙলায়ন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (49, 'নওরোজ কিতাবিস্তান',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (50, 'অবধূত বইঘর',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (52, 'ওয়াল্ড নিউজ এজেন্সি',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (55, 'নবযুগ প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (56, 'মেরিট ফেয়ার প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (57, 'নওরোজ সাহিত্য সম্ভার',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (62, 'এশিয়া পাবলিকেশন্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (64, 'রিয়া প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (65, 'সাকী পাবলিশিং ক্লাব',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (68, 'প্রান্ত প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (69, 'কলি প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (70, 'কাশবন প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (72, 'নুসরাত প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (73, 'হাসি প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (74, 'অন্তরা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (75, 'হিমু প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (77, 'নবরাগ প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (79, 'বর্ণায়ন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (82, 'মুক্তদেশ প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (86, 'মুক্তচিন্তা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (88, 'সমতট',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (89, 'আশীর্বাদ প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (90, 'রাবেয়া বুক হাউস',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (91, 'আলেয়া বুক ডিপো',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (92, 'প্রচলন প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (94, 'বর্ষাদুপুর',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (96, 'প্রগতি পাবলিশার্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (97, 'দিব্য প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (101, 'রাবেয়া বুকস্',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (414, 'শিশুকিশোর প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (417, 'বঙ্গজ প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (432, 'কোয়ান্টাম ফাউন্ডেশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (441, 'আলোকায়ন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (462, 'মাহি প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (482, 'Daffodil International University Press',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (484, 'অনুশীলন প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (529, 'অন্যপ্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (530, 'বিশ্বসাহিত্য ভবন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (531, 'অনন্যা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (533, 'উৎস প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (536, 'কথাপ্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (537, 'ভাষাপ্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (538, 'ইত্যাদি গ্রন্থ প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (540, 'শ্রাবণ প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (541, 'অনুপম প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (542, 'অন্বেষা প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (543, 'অবসর প্রকাশনা সংস্থা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (544, 'আফসার ব্রাদার্স',  'https://ds.rokomari.store/rokomari110/company/69af2f2fe544_14.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (545, 'কাকলী প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (546, 'জ্ঞানকোষ প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (547, 'পার্ল পাবলিকেশন্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (548, 'প্রতীক প্রকাশনা সংস্থা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (549, 'মাওলা ব্রাদার্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (550, 'সময় প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (552, 'সাগর পাবলিশার্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (553, 'সুবর্ণ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (557, 'আগামী প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (558, 'সাহিত্য প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (561, 'সিদ্দিকীয়া পাবলিকেশন্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (564, 'বিউটি বুক হাউস',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (565, 'বিজ্ঞান একাডেমী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (567, 'বিভাস',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (570, 'প্রথমা প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (571, 'সন্দেশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (572, 'বুক ক্লাব',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (573, 'শৈশব',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (574, 'বিদ্যাপ্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (575, 'রহমান বুকস',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (576, 'আবির বুকস',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (577, 'অঙ্কুর প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (579, 'বাংলাপ্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (580, 'সাহিত্য কথা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (581, 'সূচীপত্র',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (583, 'শোভা প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (584, 'উত্তরণ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (585, 'মূর্ধন্য',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (588, 'মাটিগন্ধা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (589, 'বাংলাদেশ শিশুকেন্দ্র',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (590, 'বিশ্বসাহিত্য কেন্দ্র',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (591, 'হাওলাদার প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (594, 'ঝিঙেফুল',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (595, 'কালিকলম প্রকাশনা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (596, 'জোনাকী প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (597, 'তাম্রলিপি',  'https://ds.rokomari.store/rokomari110/company/d79ef1da9_58.jpg');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (598, 'শিখা প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (599, 'শামীম পাবলিশার্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (600, 'তরফদার প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (601, 'তিশা বুক্‌স ট্রেড',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (602, 'বর্ণবিচিত্রা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (603, 'সুচয়নী পাবলিশার্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (604, 'ঐতিহ্য',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (605, 'অ্যাডর্ন পাবলিকেশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (606, 'Adorn Publication',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (608, 'সাহিত্যদেশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (610, 'সাহিত্যমালা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (611, 'অনিন্দ্য প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (612, 'জাগৃতি প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (613, 'অন্যরকম প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (614, 'নালন্দা',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (615, 'চারুলিপি প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (616, 'খান ব্রাদার্স অ্যান্ড কোম্পানি',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (617, 'একুশে বাংলা প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (618, 'সিসটেক পাবলিকেশন্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (619, 'শব্দশৈলী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (620, 'অক্ষর প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (624, 'জাতীয় সাহিত্য প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (625, 'গাজী প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (626, 'ঝিনুক প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (627, 'পাঞ্জেরী পাবলিকেশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (628, 'আদর্শ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (630, 'পাঠক সমাবেশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (631, 'প্রকৃতি',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (632, 'সমাচার',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (635, 'আরো প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (637, 'বৈশাখী প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (639, 'জনান্তিক',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (640, 'সৃজনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (642, 'ইতি প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (643, 'দি ইউনিভার্সেল একাডেমি',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (647, 'ন্যাশনাল পাবলিকেশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (648, 'অয়ন প্রকাশন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (650, 'সেবা প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (651, 'জিনিয়াস পাবলিকেশন্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (652, 'শিকড়',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (653, 'জয়তী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (655, 'দি স্কাই পাবলিশার্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (656, 'বুকস্‌ ফেয়ার',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (658, 'রচনা প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (660, 'আহমদ পাবলিশিং হাউজ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (661, 'জ্ঞান বিতরণী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (664, 'আজকাল প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (665, 'মিজান পাবলিশার্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (666, 'রোদেলা প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (667, 'বাতিঘর প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/ef2d496af8d4_572.gif');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (671, 'সুলেখা প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (677, 'জনতা প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (679, 'কালান্তর প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (681, 'সালাউদ্দিন বই ঘর',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (361, 'মুন পাবলিকেশন্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (375, 'শিশু কানন',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (384, 'তূর্য প্রকাশনী',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (389, 'সালমা বুক ডিপো',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (391, 'পাণ্ডুলিপি',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (404, 'এ্যাবাকাস পাবলিকেশন্স',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
INSERT INTO  PUBLISHER ( PUBLISHER_ID, NAME, IMAGE) VALUES (407, 'শিশু প্রকাশ',  'https://ds.rokomari.store/rokomari110/company/publisher.png');
